STORY4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('portfoliocv', views.port, name='port'),
    path('story1', views.story1, name='story1'),
    path('homematcool', views.homematcool, name='homematcool'),
    path('matcool', views.matcool, name='matcool'),
    path('matcool/datamatcool/', views.datamatcool, name='datamatcool'),
    path('matcool/datamatcool/detailmatcool/<int:my_id>/', views.detailmatcool, name='detailmatcool'),
    path('matcool/datamatcool/detailmatcool/<int:my_id>/hapus/', views.hapusmatcool, name='hapusmatcool')
]

main/models.py
from django.db import models

# pilihanTahun = {
    # ('1', '2020/2021'),
    # ('2', '2019/2020'),
    # ('3', '2018/2019'),
    # ('4', '2017/2018'),
    # ('5', '2016/2017'),
    # ('6', '2015/2016'),
    # ('7', '2014/2015'),
    # ('8', '2013/2014'),
    # ('9', '2012/2013')
# }

class Post(models.Model):
    matkul = models.CharField(max_length = 50)
    dosen = models.CharField(max_length = 100)
    sks = models.PositiveIntegerField()
    deskripsi = models.TextField()
    ruangan = models.CharField(max_length = 30)
    tahun = models.CharField(max_length = 10)

    def __str__ (self):
        return self.matkul

main/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    matkul = forms.CharField(required=True)
    dosen = forms.CharField(required=True)
    sks = forms.CharField(required=True)
    deskripsi = forms.CharField(widget=forms.Textarea)
    ruangan = forms.CharField(required=True)
    tahun = forms.CharField(required=True)
 
    matkul.widget.attrs.update({'class':'form-control'})
    dosen.widget.attrs.update({'class':'form-control'})
    sks.widget.attrs.update({'class':'form-control'})
    deskripsi.widget.attrs.update({'class':'form-control'})
    ruangan.widget.attrs.update({'class':'form-control'})
    tahun.widget.attrs.update({'class':'form-control'})


    class Meta:
        model = Post
        fields = ['matkul', 'dosen', 'sks', 'deskripsi', 'ruangan', 'tahun']
 

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm
from .models import Post


def home(request):
    return render(request, 'main/home.html')

def port(request):
    return render(request, 'main/port.html')

def story1(request):
    return render(request, 'main/story1.html')

def homematcool(request):
    return render(request, 'main/homematcool.html')

def matcool(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = PostForm()

    context = {
        'form' : form
    }
    return render(request, 'main/matcool.html', context)

def datamatcool(request):
    data = Post.objects.all()
    context = {
        'data' : data
    }

    return render(request, 'main/datamatcool.html', context)

def detailmatcool(request, my_id):
    data = Post.objects.get(id=my_id)
    context = {
        'data' : data
    }

    return render(request, 'main/detailmatcool.html', context)


def hapusmatcool(request,my_id):
    data = Post.objects.get(id=my_id)
    if request.method == "POST":
        data.delete()
        return redirect('main:datamatcool')
    context = {
        'data' : data
    }
    return render(request, 'main/hapusmatcool.html', context)

main/templates/main/datamatcool.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Data Mata Kuliah</title>
{% endblock meta %} {% block style %}
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  crossorigin="anonymous"
/>
<link rel="stylesheet" href="{% static 'css/style5.css' %}" />
{% endblock style %} {% block content %}

<br /><br />
<div class="container">
  <div class="col-md-12 d-flex justify-content-center mt-1">
    <h1>Inilah Jadwal Kuliah Kamu</h1>
  </div>
</div>

<div class="container">
  <div class="col-md-12 d-flex justify-content-center mt-1">
    <p>Klik <b>Mata Kuliah</b> yang diinginkan untuk melihat detailnya</p>
  </div>
</div>

<br />
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr class="table-warning">
        <th scope="col">Mata Kuliah</th>
        <th scope="col">Dosen Pengampu</th>
        <th scope="col">Ruangan</th>
      </tr>
    </thead>

    {% for instance in data%}
    <tbody>
      <tr>
        <th scope="row">
          <a href="{% url 'main:detailmatcool' instance.id %}"
            >{{instance.matkul}}</a
          >
        </th>
        <td>{{instance.dosen}}</td>
        <td>{{instance.ruangan}}</td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
  <br /><br />
  <a href="{% url 'main:matcool'%}" class="btn btn-primary" role="button"
    >Tambah Matkul</a
  >
  <a href="{% url 'main:homematcool'%}" class="btn btn-primary" role="button"
    >Home</a
  >
</div>

{% endblock content %}
<script
  src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"
></script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  crossorigin="anonymous"
></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  crossorigin="anonymous"
></script>

main/templates/main/detailmatcool.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Detail Mata Kuliah</title>
{% endblock meta %} {% block style %}
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  crossorigin="anonymous"
/>
<link rel="stylesheet" href="{% static 'css/style5.css' %}" />
{% endblock style %} {% block content %}
<br><br>

<div class="container">
  <h1>Detail Matkul {{data.matkul}}</h1>
<br>
  <table class="table table-striped">
    <tbody>
      <tr>
        <th scope="row">Mata Kuliah</th>
        <td scope="row">{{data.matkul}}</a></td>
        </tr>
    </tbody>
    <tbody>
    <tr>
        <th scope="row">Dosen Pengampu</th>
        <td scope="row">{{data.dosen}}</a></td>
        </tr>
    </tbody>
    <tbody>
    <tr>
        <th scope="row">Jumlah SKS</th>
        <td scope="row">{{data.sks}}</a></td>
        </tr>
    </tbody>
    <tbody>
    <tr>
        <th scope="row">Deskripsi</th>
        <td scope="row">{{data.deskripsi}}</a></td>
        </tr>
    </tbody>
    <tbody>
        <tr>
            <th scope="row">Ruangan</th>
            <td scope="row">{{data.ruangan}}</a></td>
            </tr>
        </tbody>
    <tbody>
    <tr>
        <th scope="row">Tahun</th>
        <td scope="row">{{data.tahun}}</a></td>
        </tr>
    </tbody>
  </table>
<br>
  <a href="{% url 'main:hapusmatcool' data.id %}"class="btn btn-danger" role="button">Hapus</a>
  <a href="{% url 'main:datamatcool'%}" class="btn btn-primary" role="button">Kembali </a>
</div>
<br>
<br>



{% endblock content %}

<script
  src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"
></script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  crossorigin="anonymous"
></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  crossorigin="anonymous"
></script>

main/templates/main/hapusmatcool.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Hapus Mata Kuliah</title>
{% endblock meta %} {% block style %}
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  crossorigin="anonymous"
/>
<link rel="stylesheet" href="{% static 'css/style5.css' %}" />
{% endblock style %} {% block content %}

<br /><br />
<div class="container">
  <form action="." method="POST">
    {% csrf_token %}
    <h2>Apakah kamu ingin menghapus mata kuliah "{{data.matkul}}" ?</h2>

    <p>Jika sudah terhapus, maka data tidak dapat dikembalikan lagi</p>
    <br />
    <p>
      <input type="submit" value="Hapus" class="btn btn-danger" role="button" />
      <a href="../" class="btn btn-primary" role="button">Kembali</a>
    </p>
  </form>
</div>
{% endblock content %}

<script
  src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"
></script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  crossorigin="anonymous"
></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  crossorigin="anonymous"
></script>

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 3 PPW Hilmy</title>
{% endblock meta %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/style3.css' %}" />
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
/>
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
  crossorigin="anonymous"
/>
{% endblock style %}

{% block content %}
<!DOCTYPE html>
    <header>
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark sticky-top">
          <a class="navbar-brand" href="#banner"><p>HAN</p></a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-lg-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#banner"
                  >Home <span class="sr-only">(current)</span></a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:homematcool'%}">MatCool</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#contact">Contact</a>
              </li>
                </a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>

    <section class="banner" id="banner">
      <div class="content1">
        <div class="hello">
          <h2>
            Hello! My Name is <br />
            <span>Hilmy<br />Akbar</span>
          </h2>
          <h1>---------------------------------</h1>
          <h3>Computer Science Student at<br />University of Indonesia</h3>
        </div>
        <div class="foto">
          <img src="{% static 'img/foto.svg' %}" class="img" />
        </div>
        <div class="custom-shape-divider-bottom-1601425543">
          <svg
            data-name="Layer 1"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 1200 120"
            preserveAspectRatio="none"
          >
            <path
              d="M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z"
              class="shape-fill"
            ></path>
          </svg>
        </div>
      </div>
    </section>

    <section class="about" id="aboutme">
      <div class="content">
        <div class="contentBox">
          <h3>About Me</h3>
          <p>
            Hi ! My name is Hilmy. I am the undergraduate student in Computer
            Science at University of Indonesia. I live in Ulujami, Jakarta.
            Designing has been a favourite. I have a huge love for simple and
            modern design. Not only designing, I love to make some cinematic
            video using my own DSLR camera. I also love to make motion graphic
            in several apps, like After Effect, Vegas Pro, etc.
          </p>
          <a class="btn" href="{% url 'main:port'%}" target="_blank">See My Portfolio & CV</a>
          <a class="btn" href="{% url 'main:story1'%}" target="_blank">See My Previous Story</a>
        </div>
        <div class="foto2">
          <img src="{% static 'img/foto2.svg' %}" class="img" />
        </div>
      </div>
    </section>

    <section class="background" id="background">
      <div class="heading">
        <h2>My Background Knowledge</h2>
      </div>
      <div class="riwayat">
        <div class="sd">
          <h3>2006-2013</h3>
          <h2>Annajah<br />Islamic<br />School</h2>
        </div>

        <div class="smp">
          <h3>2013-2016</h3>
          <h2>19 Junior<br />High<br />School<br />Jakarta</h2>
        </div>

        <div class="sma">
          <h3>2016-2019</h3>
          <h2>47 Senior<br />High<br />School<br />Jakarta</h2>
        </div>

        <div class="kuliah">
          <h3>2019-Now</h3>
          <h2>University<br />of Indonesia</h2>
        </div>
      </div>
    </section>

    <section class="skill" id="skill">
      <div class="custom-shape-divider-top-1601425893">
        <svg
          data-name="Layer 1"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 1200 120"
          preserveAspectRatio="none"
        >
          <path
            d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z"
            class="shape-fill"
          ></path>
        </svg>
      </div>
      <div class="heading">
        <h2>What can I do ?</h2>
      </div>
      <div class="icon">
        <div class="gn">
          <img src="{% static 'img/gd.png' %}" class="img" />
          <h1>--------------------------</h1>
          <h3>Graphic Design</h3>
        </div>
        <div class="pg">
          <img src="{% static 'img/pg.png' %}" class="img" />
          <h1>--------------------------</h1>
          <h3>Photography</h3>
        </div>
        <div class="vd">
          <img src="{% static 'img/vd.png' %}" class="img" />
          <h1>--------------------------</h1>
          <h3>Cinematography</h3>
        </div>
      </div>
    </section>

    <section class="experience" id="experience">
      <div class="heading">
        <h2>My Experiences</h2>
      </div>
      <div class="kotak">
        <div class="shifted">
          <img src="{% static 'img/shifted.png' %}" class="img" />
          <div class="teks1">
            <h3>Head of<br />Documentation</h3>
            <p>The 3rd Recital Teater Citra 47 "Shifted"<br />2017</p>
          </div>
        </div>
        <div class="wisgan">
          <img src="{% static 'img/wisgan.png' %}"class="img" />
          <div class="teks2">
            <h3>Staff of Creative</h3>
            <p>Wisuda Ganjil Fasilkom<br />2020</p>
          </div>
        </div>
        <div class="perak">
          <img src="{% static 'img/perak.png' %}" class="img" />
          <div class="teks3">
            <h3>Staff of Bazaar</h3>
            <p>Pesta Rakyat Komputer Fasilkom<br />2020</p>
          </div>
        </div>
        <div class="compfest">
          <img src="{% static 'img/compfest.png' %}" class="img" />
          <div class="teks4">
            <h3>Staff of Digital Marketing</h3>
            <p>COMPFEST<br />2020</p>
          </div>
        </div>
      </div>
    </section>

    <section class="contact" id="contact">
      <div class="heading">
        <h2>Keep in Touch !</h2>
        <h3>Need a hand ? or a high five ? Here's how to reach me</h3>
        <p>hilmy.akbar@ui.ac.id</p>
      </div>
      <div class="socialmedia">
        <div class="icon">
          <ul>
            <li>
              <a href="https://www.facebook.com/hilmyakbar34" target="_blank"  rel="noopener noreferrer"
                ><i class="fa fa-facebook"></i
              ></a>
            </li>
            <li>
              <a href="https://twitter.com/helmeeyyy" target="_blank"  rel="noopener noreferrer"
                ><i class="fa fa-twitter"></i
              ></a>
            </li>
            <li>
              <a href="https://www.instagram.com/hilmy34" target="_blank" rel="noopener noreferrer"
                ><i class="fa fa-instagram"></i
              ></a>
            </li>
            <li>
              <a
                href="https://www.youtube.com/user/hilmyakbar23"
                target="_blank"  rel="noopener noreferrer"
                ><i class="fa fa-youtube"></i
              ></a>
            </li>
            <li>
              <a
                href="https://www.linkedin.com/in/hilmy-akbar-5aa1081a3/"
                target="_blank" rel="noopener noreferrer"
                ><i class="fa fa-linkedin"></i
              ></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="footer">
        <img src="{% static 'img/footer.svg' %}" class="img" />
      </div>
    </section>

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
    <script>
      var scroll = new SmoothScroll('a[href*="#"]');
      speed: 300;
    </script>
{% endblock content %}

main/templates/main/homematcool.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>MatCool</title>
{% endblock meta %} {% block style %}
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  crossorigin="anonymous"
/>
<link rel="stylesheet" href="{% static 'css/style5.css' %}" />
{% endblock style %} {% block content %}

<header>
  <div class="container">
    <div class="banner-text">
      <div class="text-area">
        <h1><span>Mat</span>Cool.</h1>
        <h2>Atur jadwal mata kuliah kamu !</h2>
        <p class="banner-btn">
          <a href="{% url 'main:matcool'%}" class="active">Tambah Jadwal</a>
          <a href="{% url 'main:datamatcool'%}" class="active">Lihat Jadwal</a>
          <a href="{% url 'main:home'%}" class="active">Kembali</a>
        </p>
      </div>
    </div>
  </div>
</header>

{% endblock content %}
<script
  src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"
></script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  crossorigin="anonymous"
></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  crossorigin="anonymous"
></script>

main/templates/main/matcool.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Mata Kuliah</title>
{% endblock meta %} {% block style %}
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  crossorigin="anonymous"
/>
<link rel="stylesheet" href="{% static 'css/style5.css' %}" />
{% endblock style %} {% block content %}

<div class="container">
  <div class="col-md-12 d-flex justify-content-center mt-5">
    <h1 style="font-family: Rubik, sans-serif">Masukkan Jadwal Kamu !</h2>
  </div>
</div>
<div class="container">
  <div class="col-md-12 d-flex justify-content-center mt-1">
    <p style="font-family: Rubik, sans-serif">
      Bersiaplah untuk menjadi orang yang terorganisir
    </p>
  </div>
</div>

<div class="container mt-2">
  <div class="row d-flex justify-content-center">
    <div class="col-lg-6">
      <div class="form-group">
        <form method="POST" style="font-family: Rubik, sans-serif">
          {% csrf_token %} {{form.as_p}}
          <br />
          <button type="Submit" class="btn btn-success">Save</button>
          <a class="btn btn-primary" href="{% url 'main:datamatcool'%}"
            >Lihat Jadwal</a
          >
          <a class="btn btn-primary" href="{% url 'main:homematcool'%}"
            >Kembali</a
          >
          <br />
        </form>
      </div>
    </div>
  </div>
</div>
<br>
<br>
{% endblock content %}

<script
  src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
  crossorigin="anonymous"
></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.min.js"
  integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
  crossorigin="anonymous"
></script>

main/templates/main/port.html
{% extends 'base.html' %} {% load static %} {% block meta %} {% block style %}
<link rel="stylesheet" href="{% static 'css/style3.css' %}" />
{% endblock style %}
<title>Portfolio and CV</title>
{% endblock meta %} {% block content %}
<section class="portfolio">
  <a
    href="https://drive.google.com/drive/folders/1sTFHZqc7t5B4zsqx8tNXKt91mZk3Nd32?usp=sharing"
    target="_blank"
    rel="noopener noreferrer"
    ><h3>Click here to see my Portfolio and CV</h3></a
  >
  <h2>Also, you can watch my projects below</h2>
  <div class="video">
    <iframe
      width="560"
      height="315"
      src="https://www.youtube.com/embed/80eCxuUsEG0"
      frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen
    ></iframe>
  </div>
  <div class="video2">
    <iframe
      width="560"
      height="315"
      src="https://www.youtube.com/embed/k-RMWa4yaZs"
      frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen
    ></iframe>
  </div>
  <a
    href="https://drive.google.com/drive/folders/1XxZ91CJj1OjXsSGtU1LktfLPhhQZ23wu?usp=sharing"
    target="_blank"
    rel="noopener noreferrer"
    ><h3>sst.. Click here to see my other projects</h3></a
  >
</section>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %} {% block style %} {% endblock style %}
  </head>

  <body></body>
  {% block content %} {% endblock content %}
</html>